- shell:
  - sudo apt update -y
  - [sudo apt install -y build-essential autoconf automake pkg-config libevent-dev libncurses5-dev bison, Install tmux dependencies]
  - [rm -rf /tmp/tmux && git clone https://github.com/tmux/tmux.git /tmp/tmux && cd /tmp/tmux && git checkout 3.2 && sh autogen.sh && ./configure && make && sudo make install, Build tmux 3.2 from scratch]
  - [sudo gem install tmuxinator, Install tmuxinator]
