- shell:
    - [
        sudo apt install -y software-properties-common && sudo add-apt-repository -y ppa:neovim-ppa/unstable,
        Add neovim repository,
      ]
    - [
        sudo apt install -y sudo git lua5.1 python3-dev python3-venv cmake nodejs locales curl silversearcher-ag global clang-format universal-ctags zsh fzf,
        Install plugin dependencies,
      ]
    - [
        curl -LO https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb && sudo dpkg -i ripgrep_12.1.1_amd64.deb,
        Install ripgrep,
      ]
    - [sudo apt install -y neovim, Install neovim]
    - [sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60, Make neovim default]

- shell:
    - [
        curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh && chmod +x nodesource_setup.sh && ./nodesource_setup.sh && sudo apt-get install nodejs -y,
        Install newer npm,
      ]
    - [npm install -g fixjson neovim jsonlint prettier yarn, Install linters]
