- create:
  - ~/.config/nvim

- link:
    ~/.vim: vim/vim
    ~/.ideavimrc: vim/vimrcs/ideavimrc
    ~/.config/nvim/init.vim: vim/init.vim
    ~/.config/nvim/lua: vim/lua

- shell:
  - [vim/install_awesome_vimrc.sh, Installing vimrc]
  - [pip3 install --upgrade pynvim trash-cli, Install neovim plugin manager ]
  - [curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim, Download Plug.vim]
  - 
    command: nvim --headless +PlugInstall +qall
    stdout: true
    stderr: true
    quiet: false
    description: Install plugins via Vim-Plug
  - [nvim --headless +PlugUpdate +qall, Update all plugins via Vim-Plug]

- create:
  - ~/.vim/temp_dirs
  - ~/.vim/temp_dirs/undodir
