- create:
  - ~/.config/nvim

- link:
    ~/.vim: vim/vim
    ~/.ideavimrc: vim/vimrcs/ideavimrc
    ~/.config/nvim/init.vim: vim/init.vim

- shell:
  - [vim/install_awesome_vimrc.sh, Installing vimrc]
  - [pip3 install --user --upgrade pynvim, Install neovim plugin manager ]
  - [curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim, Download Plug.vim]
  - [nvim --headless +PlugInstall +qall, Install plugins via Vim-Plug]
  - [nvim --headless +PlugUpdate +qall, Update all plugins via Vim-Plug]

- create:
  - ~/.vim/temp_dirs
  - ~/.vim/temp_dirs/undodir
