- defaults:
    link:
      create: true
      relink: true

- create:
    - $HOME/.config

- clean: ['~']

- shell:
  - [git submodule update --recursive --init, Installing/updating submodules]
  - ['[ -x "$(command -v apt)" ] && apt update; echo Ignore', Update apt mirrors]
  - [pip3 install wheel, Install wheel]
