# Path to your oh-my-zsh installation.
export ZSH="$HOME/.config/zsh/oh-my-zsh"

ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
    vi-mode
    git
    zsh-autosuggestions
    history-substring-search
    docker docker-compose
    zsh-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh

# User configuration

zmodload zsh/terminfo

# Bind zsh-augosuggestions to Ctrl+N
bindkey '^n' autosuggest-accept

bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Use ranger to switch directories and bind it to ctrl-o
ranger_cd () {
    tmp="$(mktemp)"
    ranger --choosedir="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
bindkey -s '^o' 'ranger_cd\n'

# Remove computer and user names from terminal prompt
prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)"
  fi
}

# User specific environment
export SKY="$HOME/skycoin"
export DEVICE_TYPE=USB
export UCU="$HOME/ucu/"

export SCP_PRIVKEY=c2ab96e87e7154ed4764bf5769229b892494fd944448a03e3852c5714be84a08

export GOPATH="$SKY/go"
PATH="$HOME/.local/bin:$HOME/bin:$GOPATH/bin:$PATH"

alias sleep='dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Suspend" boolean:true'
